### ISSUE TITLE
Dockerized tests fail

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni#12]
When I tried to automatically run all available tests in the `test-suite`-folder for #3, I realized that the dockerized tests (`make linux_docker`) do always fail on centos with:
```
[java] There was 1 failure:
[java] 1) test(com.dropbox.djinni.test.WcharTest)
[java] junit.framework.ComparisonFailure: expected:<...string with unicode [], ?, ? symbols> but was:<...string with unicode [], ?, ? symbols>
```
Full log: https://github.com/jothepro/djinni/runs/851151937?check_suite_focus=true

I did not investigate any further yet.
Additionally I have concerns to how useful these tests are, since they only test the java-bridging on a few distribution/compiler configurations. Instead I think it might be more useful to run more extensive matrix-tests with github-actions.

**Comment by a4z** [comment]
I think it is save to close that issue now :-)
