### ISSUE TITLE
IntelliJ Plugin does not support `flags`

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni#19]
# Summary 
The IntelliJ Djinni Plugin published on the [Jetbrains Marketplace](https://plugins.jetbrains.com/plugin/9209-djinni-idl-file-support) does not support `flags`:

<img width="430" alt="Bildschirmfoto 2020-10-10 um 18 40 59" src="https://user-images.githubusercontent.com/21294002/95660535-d5e3b700-0b28-11eb-9a71-b5b49a2122dd.png">

# How to reproduce:
Install the Plugin in IntelliJ IDEA and create a `.djinni` file. Define a `flags`-datatype like so:
```
my_flags = flags {
  flag1;
}
```
The IDE will now hint you that it does not know about the `flags` keyword.

**Comment by a4z** [comment]
wow, I have seen the folder but did not fully realise that this is part of this repo, one more thing to split out into an extra project , #17 :-)

**Comment by jothepro** [comment]
Closed in favor of https://github.com/cross-language-cpp/djinni-intellij-plugin/issues/13
