### ISSUE TITLE
What about the python-branch?

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni#20]
There is a branch that brings experimental python-support. I do understand why dropbox kept this in a feature-branch, because it never was in their personal interest & scope to support python.

Has anyone used the python branch? How do you think about it? Should we continue to focus on Java & ObjC or should we also be open to other languages? 

My opinion:
I'd prefer merging python support into master (if it's feature-complete & works) and mark it as experimental in the documentation. Personally I have no interest in python support, but I think maintenance of the project will be easier if changes don't have to be ported over to the python-branch manually.
If we should find out that the python branch is not feature complete (it seems like it lacks any documentation, wich is a warning sign to me), I'd prefer dumping the branch instead of having to somehow maintaint it.

**Comment by a4z** [comment]
There is this (re-implementation?) 
https://github.com/pyginny/pyginny

one of the positive possible side effects from #17 might be that it becomes more easy to add additional implementations.
since the tests for the generator are basically text in - text out, the thing in between becomes interchangeable.
Once the repos are stand alone, by seeing a the subset of the problem, it might be more motivating to contribute

**Comment by jothepro** [comment]
The python-branch is about adding support for generading python-gluecode. It's not about a python-reimplementation.

**Comment by a4z** [comment]
Ah of course, sorry for wrong thinking.

Sure, you are right, I also think it is better to have something visible, but marked as experimental, than hide it in a branch where it most likely will start to become rotten.

**Comment by richey-v** [comment]
FYI...  I experimented with the python branch, specifically 342636e4826ba208d738ee8ef6403a58d807ad64 (latest in a few forks including this one).  I would definitely call it "experimental".  When trying it, I was already using a number of the `--ident` and `--cpp-out` switches which the Python generator did not respect at all and so had many headaches getting it to build.  I gave up at that point, planning to return to it eventually.

**Comment by jothepro** [comment]
This can be closed thanks to the contribution from @freitass in [djinni-generator](https://github.com/cross-language-cpp/djinni-generator/pull/43) & [djinni-support-lib](https://github.com/cross-language-cpp/djinni-support-lib/pull/24). The Python support, while still being considered experimental, will be merged to master in both compontents soon!
