### ISSUE TITLE
Logo/Icon for djinni?

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni#21]
This may be a bit off-topic but while refreshing the intellij plugin I realized that I wanted to update the **file icon** for djinni files + I want to include a **logo** for the plugin.

So I wasted my time by making this new logo design for djinni:
![djinni_logo_idea_2](https://user-images.githubusercontent.com/21294002/96039623-3ea09b80-0e69-11eb-91fc-6c793e490ceb.png)

It's pretty basic but I made it from scratch, so no copyright/licensing issues!  😎
The font is [Overpass](https://fonts.google.com/specimen/Overpass?query=overpass), should be free to use.
I know I will hate it in a few days, but I love it right now! 

What do you think?

**Comment by a4z** [comment]
I love it! 
How did you do that? Gimp? This looks gorgeous!

**Comment by jothepro** [comment]
Affinity designer :) With this image as a template https://warisanlighting.com/wp-content/uploads/2016/06/magic-lamp-genie-photo-7.jpg 😁

**Comment by a4z** [comment]
I think we can say the logo is great and shall be used, so maybe this issue can also be closed?

**Comment by jothepro** [comment]
I am planning to publish the raw files in some way or another, so others can use & modify them. I'm not sure yet where to put them. Maybe in the not yet existing central documentation in https://github.com/cross-language-cpp/djinni-documentation ?

**Comment by a4z** [comment]
good idea, I think this seems to be a good place, it will be required there anyway

**Comment by jothepro** [comment]
closed in favor of https://github.com/cross-language-cpp/djinni-documentation/issues/1
