### ISSUE TITLE
Wipe out the code and replace it with a README providing all info about the new project structure

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/djinni#27]
We have now multiple examples where people think this repo is the new official one, and the info about the repo split is not picked up.
We need to make this more visible.

My suggestion: make a new commit where all the code is removed, and only a README.md is left, explaining the most important details. 

If you also think this is OK, @jothepro , than I will do that.

**Comment by jothepro** [comment]
Thats a good idea!
