### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni#4]
As a project maintainer I want everybody participating in this repository to commit to a code of conduct that promotes a open and diverse community and protects it from getting unhealthy.

I would prefer to just copy and modify someone elses COC, like for example the one from [apache](http://apache.org/foundation/policies/conduct.html)

**Comment by a4z** [comment]
I agree to the  copy and paste approach.
Here is some information, including some popular template that got adopted by very many other peojects, that could be helpful.
https://opensource.guide/code-of-conduct/
