### ISSUE TITLE
automatically publish djinni as jar with each release

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni#9]
As a user I want to easily download the latest djinni release as a binary without messing around with building it, because it is faster and easier than running the makefile myself.

This could be achieved by extending the pipeline to build and publish the jar resulting from `make djinni_jar` on each release tag.

**Comment by a4z** [comment]
I think the github actions you are working on are a step into the right direction

**Comment by jothepro** [comment]
closed in favor of https://github.com/cross-language-cpp/djinni-generator/issues/4
